[package]
name = "tokio-issue-6325-storage-full"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
rand = "0.8.5"
tokio = { version = "1.36.0", features = ["full"] }
